# All services are imported from the main docker-compose.yaml file,
# except tests, which is defined here.

services:
  key-generator:
    extends:
      file: docker-compose.yaml
      service: key-generator
  key-server:
    extends:
      file: docker-compose.yaml
      service: key-server
  gwmilter:
    extends:
      file: docker-compose.yaml
      service: gwmilter
  postfix-gw:
    extends:
      file: docker-compose.yaml
      service: postfix-gw
  mailpit:
    extends:
      file: docker-compose.yaml
      service: mailpit
  tests:
    build:
      context: ..
      dockerfile: integrations/tests-runner/Dockerfile
    depends_on:
      key-generator:
        condition: service_completed_successfully
      key-server:
        condition: service_healthy
      gwmilter:
        condition: service_healthy
      postfix-gw:
        condition: service_healthy
      mailpit:
        condition: service_healthy
    volumes:
      - ../tests:/tests:rw
      - ../integrations/keys:/app/keys:ro
      - /var/run/docker.sock:/var/run/docker.sock
    working_dir: /
    networks:
      - gwmilter_network

volumes:
  gwmilter-gnupg:


networks:
  gwmilter_network:
    driver: bridge
